creation of the endpoint that lists all users
alkemyTech/OT221-server pull request #16
Opened 2022-06-27 02:59 UTC by MarcosSWeis

![image](https://user-images.githubusercontent.com/91438906/175851245-658cd80e-2586-4f55-96f7-da1e7527416c.png)
 el endpoint devuelve un objeto que dentro tiene el total de usuarios , que va a servir para el paginado, para no traer  un array gigante en el caso que sean muchos  usuarios . Dicho objeto también tiene dentro  un array con los usuarios  en este caso lo limite a 10 usuarios  pero pueden ser mas, a cada usuario se le elimino la contraseña por seguridad

2022-06-28 19:47 UTC, GauntStrelok commented
Eliminar el archivo package-lock.json asi no genera conflictos con otros

2022-06-30 05:26 UTC, GauntStrelok commented
Hacer pull de main para arreglar conflictos

2022-07-01 00:57 UTC, GauntStrelok requested changes
Arreglar los errores de merge y hacer pull de main para traer los nuevos conflictos

2022-07-01 00:57 UTC, GauntStrelok commented on src/controllers/users-controllers.js
> +<<<<<<< HEAD
Mal mergeado, arreglar el merge

2022-07-01 17:21 UTC, MarcosSWeis commented
![image](https://user-images.githubusercontent.com/91438906/176941234-9b80f673-1a28-4058-9526-074f9dc54b58.png)
todo sigue andando
cambie varias cosas pablos de archivos y  me di cuenta que no estaba respetando en lo que habíamos quedado con los chicos, que era que era conntroller , service, respositori. Estaba haciendo todo en el servicio yo, así que ahí modifique eso , y acomode los archivos de las rutas porque uno ya no servía

2022-07-03 19:43 UTC, merged

2022-07-03 19:44 UTC, GauntStrelok commented on src/controllers/users-controller.js
> +        const page = query.page - 1;
el tema de la pagina esta medio raro, es mucho mejor definir en el contrato que la pagina empieza desde 0, a que vos tengas que hacer este calculo raro para obtener la pagina(ademas, la mayoria de las cosas que se hacen con programacion, todos saben que la pagina inicial es la pagina 0)

2022-07-03 19:45 UTC, GauntStrelok commented on src/controllers/users-controller.js
> +        const page = query.page - 1;
Igualmente, me gusto el paginado aunque no estaba pedido